###########
# site.title

title: Anup B. Rao
description: Research Scientist at Adobe Research - Fast Algorithms, Machine Learning, and Causal Inference
url: "https://raoanupb.github.io"
host: 127.0.0.1


#########################
# more settings

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

sass:
  sass_dir: css
  style:    compressed

baseurl: ""
permalink: pretty
timezone: America/New_York
future: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

collections:
  publications:
    output: true
    permalink: /:collection/:path/

include:
  - .htaccess
  - _pages
  - files
  
exclude:
- README.md
- LICENSE.md

# Site Author
author:
  name             : "Anup B. Rao"
  avatar           : "me.jpg"
  bio              : "Research Scientist at Adobe Research"
  location         : "San Jose, CA"
  employer         : "Adobe Research"
  pubmed           :
  googlescholar    :
  email            :
  researchgate     :